dist: focal
language: node_js
addons:
  chrome: stable
branches:
  only:
    - develop
    - staging
    - prod
env:
  global:
    - REPO_NAME="${PWD##*/}"
    - AWS_REGION="us-east-1"
install:
  # install awscli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip && sudo ./aws/install
  # install other tools
  - pip install travis-wait-improved awsebcli
before_script:
  # Setup AWS CLI profile for multiple AWS accounts
  - mkdir -p ~/.aws
  - echo -e "[profile develop]\nsource_profile=ci-user-develop\nrole_arn=${AwsCfServiceRoleArn_develop}\n" > ~/.aws/config
  - echo -e "[ci-user-develop]\naws_access_key_id=${AwsTravisAccessKey_develop}\naws_secret_access_key=${AwsTravisSecretAccessKey_develop}\n" > ~/.aws/credentials
  - echo -e "[profile prod]\nsource_profile=ci-user-prod\nrole_arn=${AwsCfServiceRoleArn_prod}\n" >> ~/.aws/config
  - echo -e "[ci-user-prod]\naws_access_key_id=${AwsTravisAccessKey_prod}\naws_secret_access_key=${AwsTravisSecretAccessKey_prod}\n" >> ~/.aws/credentials
  # setup npm dependencies and clean
  - npm install
  - npm run clean:npm
stages:
  - name: test
  - name: eb-deploy-develop
    if: (tag =~ ^v) OR (type = push) AND (branch = develop)
  - name: eb-deploy-staging
    if: (tag =~ ^v) OR (type = push) AND (branch = staging)
  - name: eb-deploy-prod
    if: (tag =~ ^v) OR (type = push) AND (branch = prod)
jobs:
  include:
    - stage: test
      script:
        - export NODE_OPTIONS=--max_old_space_size=4096
        - npm run ci:travis
      node_js: 16
    - stage: deploy-develop
      script:
        - ./scripts/set-agora-version.sh || travis_terminate 1
        - zip /tmp/agora-app.zip -qr9 * .[^.]*
        - eb deploy --profile develop --verbose --region ${AWS_REGION} --staged agora-develop
    - stage: deploy-staging
      script:
        - ./scripts/set-agora-version.sh || travis_terminate 1
        - zip /tmp/agora-app.zip -qr9 * .[^.]*
        - eb deploy --profile prod --verbose --region ${AWS_REGION} --staged agora-staging
    - stage: deploy-prod
      script:
        - ./scripts/set-agora-version.sh || travis_terminate 1
        - zip /tmp/agora-app.zip -qr9 * .[^.]*
        - eb deploy --profile prod --verbose --region ${AWS_REGION} --staged agora-prod
