sudo: required
dist: focal
language: node_js
cache:
  npm: false

addons:
  chrome: stable

branches:
  only:
    - develop
    - staging
    - prod

before_install:
  - npm install npm@8.11.0
  - npm cache verify
  - travis_retry npm prune

install:
  - npm install

before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096

stages:
  - name: test
  - name: eb-deploy-develop
    if: (tag =~ ^v) OR (type = push) AND (branch = develop)
  - name: eb-deploy-staging
    if: (tag =~ ^v) OR (type = push) AND (branch = staging)
  - name: eb-deploy-prod
    if: (tag =~ ^v) OR (type = push) AND (branch = prod)

jobs:
  fast_finish: true
  include:
    - stage: test
      script: npm run ci:travis
      node_js: 16
    - stage: eb-deploy-develop
      script:
        - ./scripts/set-agora-version.sh || travis_terminate 1
        - zip /tmp/agora-app.zip -qr9 * .[^.]*
      node_js: 16
      deploy:
        - provider: elasticbeanstalk
          edge: true  # opt in to dpl v2
          cleanup: true
          bucket: org-sagebase-agora-deployment-agora-develop
          zip_file: /tmp/agora-app.zip
          region: us-east-1
          app: agora-ampad
          env:
            develop: agora-develop
            DISABLE_OPENCOLLECTIVE: true
          wait_until_deployed: true
          access_key_id: AKIAY22FMBNE7T3Q36PT
          secret_access_key:
            secure: "kjYluQ9s2QO3jiL8fqIrPOuhxfPTNLUJEELnJNXQGwSd+WCcYzax4r8iKQr7Lkb7vCn1KqKYtTlub5bTm/7jgqYVhQlFsKr/W0u6mFMBBUcwSm3R/3gMbyzWpvpLQDqLiUX9lt3u69u82pAiJO70EQ7Ybe4g+QgnMfRF3N39TwcY6kBMelXsCAdb/PRqZFCYx1kQEqVpzvOih0XpNWurhQ7ivXP48OEWjDy7H3We+QVb4AXJEpSrP2QJ6udnHBBsmj2zJ/uwEBbmVxq8JFIURNdbz2Wda5Lm/7FO8QNt558VI5L3HWd73fxztyhEOhmYHjQPxLCScoV2Mw8rAEP0DfNL8zKIGEzQOhSw1uQ8gSd9sdfC5hL+dtTlH2qUfhFM6cKCHB4QSQ+hyQi/k5PYr2tTfymnrieHj0laFx+ge6pDrdla0SH/zEQFgwdlI8Mih27tdbY6yQ6A8BT23Kl45IWzHtMgKujHeN4TR/SHrQRUTZOoD9ryh5NDGrDICii6SZL73QAhep9Smue9D0ThbNLt0stPxaklCuJhT/qi+m5RUg/uICxI/4EYPqMLYrHya8m1gJfDYyEMTQSsjypViRdov/q3K2eymDM7Qr3kgqWI3sWaHWxQqtSqMhgxCF8ozVlM2U60uiW4XhnL2iAh+7xMSQ5Ztou6nZ09nvx6qC8="
    - stage: eb-deploy-staging
      script:
        - ./set-agora-version.sh || travis_terminate 1
        - zip /tmp/agora-app.zip -qr9 * .[^.]*
      node_js: 16
      deploy:
        - provider: elasticbeanstalk
          edge: true  # opt in to dpl v2
          cleanup: true
          bucket: org-sagebase-agora-deployment-agora-staging
          zip_file: /tmp/agora-app.zip
          region: us-east-1
          app: agora-ampad
          env:
            staging: agora-staging
            DISABLE_OPENCOLLECTIVE: true
          wait_until_deployed: true
          access_key_id: AKIAZ5GJ3GCELHWLMUUX
          secret_access_key:
            secure: "pdkHMHxbptv7ycSaTKBHihsy58h1z9b1dGg/W70KGJVNdyTFtHqgEDAfhE/ppxtygo6f9OdZl20InMKqjQ827Hgf6VYbcU5Lrc3c1k3bHMwXOySZcWoElDd3RT9a1s4tQA3SVo3lQZ4MSLTR5D/IBUkHvCOO/+v56ZyaEMfKcZ+ditIyowOt8KAlcTbYAGZvZnR5NTClUMvDZiBn5v+06DP18qcqNiG4JS13lIbLgNHtIRE1tFoQ7qKO/VfeNdYIvMNHbGRedNMX/mEwM/tefb0r6Wdw2a6vOxftzUQMg7bh0mrgn5YxXtCP9ec0rx0RS2iv31ZQt6yTPowoCXekq39RyRHgO56MmiHwH2UarGFPAA7FQ7qdxk9uU0uxrxqBl9V39UsoSGEffGLjaJoDXdcwubbTMtbnsDMLeTv/Zl+QVWVyPRLIy2iH9671fjPLoCGLmT3iDz38z4La5lvEKHYf4srektVLLd0xDryMXIjGlkwI5wIQDTZWzG67tu59OIn6nU8PFQvDD27muetw70zAx2yir9aphBgGtZSPB9jMy8olaw/J4r5PqElr4Qaed7SUPYdnzTdiwEVmCyepec3ftOjfQHatdWDxJsT854nHpxmwWcQQOGAh4q/HCr46aNJw5di3k5EWHpj6M0ktBS6T9bRsW1JYiBGQ/DBdpMk="
    - stage: eb-deploy-prod
      script:
        - ./set-agora-version.sh || travis_terminate 1
        - zip /tmp/agora-app.zip -qr9 * .[^.]*
      node_js: 16
      deploy:
        - provider: elasticbeanstalk
          edge: true  # opt in to dpl v2
          cleanup: true
          bucket: org-sagebase-agora-deployment-agora-prod
          zip_file: /tmp/agora-app.zip
          region: us-east-1
          app: agora-ampad
          env:
            prod: agora-prod
            DISABLE_OPENCOLLECTIVE: true
          wait_until_deployed: true
          access_key_id: AKIAZ5GJ3GCELHWLMUUX
          secret_access_key:
            secure: "pdkHMHxbptv7ycSaTKBHihsy58h1z9b1dGg/W70KGJVNdyTFtHqgEDAfhE/ppxtygo6f9OdZl20InMKqjQ827Hgf6VYbcU5Lrc3c1k3bHMwXOySZcWoElDd3RT9a1s4tQA3SVo3lQZ4MSLTR5D/IBUkHvCOO/+v56ZyaEMfKcZ+ditIyowOt8KAlcTbYAGZvZnR5NTClUMvDZiBn5v+06DP18qcqNiG4JS13lIbLgNHtIRE1tFoQ7qKO/VfeNdYIvMNHbGRedNMX/mEwM/tefb0r6Wdw2a6vOxftzUQMg7bh0mrgn5YxXtCP9ec0rx0RS2iv31ZQt6yTPowoCXekq39RyRHgO56MmiHwH2UarGFPAA7FQ7qdxk9uU0uxrxqBl9V39UsoSGEffGLjaJoDXdcwubbTMtbnsDMLeTv/Zl+QVWVyPRLIy2iH9671fjPLoCGLmT3iDz38z4La5lvEKHYf4srektVLLd0xDryMXIjGlkwI5wIQDTZWzG67tu59OIn6nU8PFQvDD27muetw70zAx2yir9aphBgGtZSPB9jMy8olaw/J4r5PqElr4Qaed7SUPYdnzTdiwEVmCyepec3ftOjfQHatdWDxJsT854nHpxmwWcQQOGAh4q/HCr46aNJw5di3k5EWHpj6M0ktBS6T9bRsW1JYiBGQ/DBdpMk="
