sudo: required
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- '6'
- '7'
- '8'
matrix:
  fast_finish: true
before_install:
- npm install npm@5 -g
- npm cache verify
- npm prune
- npm update
install:
- npm install
after_install:
- npm rebuild node-sass
before_script:
- node ./node_modules/protractor/bin/webdriver-manager update
- npm rebuild node-sass
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run ci:travis
env:
  global:
    secure: UbBiBwnojdW7zxo6Pd3XHDjNrNMKm8kEbvugcxRv0sFtYqOz2+wjKRBkTcRyjcuFnw10NL5zF1U+qmgIG7tWHh1xwyLvRmyKJd10Z92yg2oESJvbPRgGj/cwcMXNf04gENdOcRzrDXpsQhg7Vngcx2+5Fd8HZUgm27ogCTceWiwCh023F/o4HJkGSSkWq0XSzTfU6fdLpa2+Yv9ub2B6iGrn5qkaClksafYH0dHos0v1MmhtixQi9Yhref6tnOVBPjfBhoFcajm4XzU7dRWPs5fbvPjTLuHQIP01DGCs9Co+gKi1e4v/cEi3b+ynIevrq3rqIuDZT4QsKE9kqnEDgbKvqetLhubkB1H6OBs54L08qyZhFr7+2+7ELBrjiMD3yWMXepMkV9XTE0wLEJVpMxdaeOHSVz7EG9xhDGtj0BICeqoje9s6bwkUItTf4VUTmONYdrBOgdLAZYaKwGJjxCknBXNuQJTHDxQfNW/hgsUgAblKPBQTPvhtKl1O9CijC/wfi8Z8YlW/LSOPA4BVp5ujnx7sMk+7SygEocaCOtmMs3nYwbdghWZNW7zWLpL3YfJHhRXyVj5HB7y957+eAiCOEyC31aFWdTKOqKhr1tvZAPo9hbxuF6rbVzqBNZvUccBp+JYBTJnOaNWFj7ZUo9g2+qQXNTEAmBaUeK4hfTg=
