version: '3'
services:
  wall-of-targets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wall-of-targets
    environment:
      - MONGO_URI=mongodb://mongodb/walloftargets
    links:
      - mongodb
    ports:
     - '3000:3000'
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb
